// <auto-generated />
namespace CalenderEventAsp.NetFrameworkProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migfirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migfirst));
        
        string IMigrationMetadata.Id
        {
            get { return "202507260633079_mig-first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
